import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {FaArrowRight,FaBars,FaBolt,FaCheckCircle,FaChevronDown,FaClock,FaCreditCard,FaHeart,FaHome,FaMapMarkerAlt,FaMinus,FaMoon,FaPlus,FaReceipt,FaSearch,FaShoppingBag,FaSignInAlt,FaStar,FaSun,FaTimes,FaTruck,FaUser,FaUtensils,FaWallet,FaFacebookF,FaInstagram,FaTwitter,FaGithub} from 'react-icons/fa';
import './styles.css';

const restaurants=[
{id:1,name:'Ember & Crust',cuisine:'Italian • Pizza',rating:4.9,time:'20–30 min',fee:'Free delivery',open:true,img:'https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=900&q=80',tag:'Top rated'},
{id:2,name:'Saffron Street',cuisine:'Indian • North Indian',rating:4.8,time:'25–35 min',fee:'₹20 delivery',open:true,img:'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=80',tag:'Popular'},
{id:3,name:'Green Bowl Co.',cuisine:'Healthy • Salads',rating:4.7,time:'15–25 min',fee:'Free delivery',open:true,img:'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=80',tag:'Healthy pick'},
{id:4,name:'Burger District',cuisine:'American • Burgers',rating:4.6,time:'20–30 min',fee:'₹15 delivery',open:false,img:'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=80',tag:'Best seller'}
];
const foods=[
{id:1,name:'Truffle Margherita',restaurant:'Ember & Crust',category:'Pizza',price:349,rating:4.9,pop:98,desc:'Wood-fired crust, tomato, mozzarella & truffle oil.',img:'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=800&q=80',veg:true},
{id:2,name:'Smoky Paneer Tikka',restaurant:'Saffron Street',category:'Fast Food',price:289,rating:4.8,pop:94,desc:'Charred paneer, peppers and signature smoky masala.',img:'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&w=800&q=80',veg:true},
{id:3,name:'Crispy Zinger Burger',restaurant:'Burger District',category:'Burgers',price:259,rating:4.7,pop:96,desc:'Crunchy fillet, lettuce, pickles and house sauce.',img:'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',veg:false},
{id:4,name:'Mango Berry Bowl',restaurant:'Green Bowl Co.',category:'Healthy Meals',price:229,rating:4.8,pop:91,desc:'Fresh mango, berries, granola and coconut yogurt.',img:'https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38?auto=format&fit=crop&w=800&q=80',veg:true},
{id:5,name:'Loaded Peri Peri Fries',restaurant:'Burger District',category:'Fast Food',price:179,rating:4.6,pop:89,desc:'Golden fries tossed in peri-peri seasoning and cheese.',img:'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=800&q=80',veg:true},
{id:6,name:'Chocolate Lava Cake',restaurant:'Ember & Crust',category:'Desserts',price:199,rating:4.9,pop:93,desc:'Warm chocolate cake with a molten center.',img:'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80',veg:true},
{id:7,name:'Classic Cold Coffee',restaurant:'Green Bowl Co.',category:'Beverages',price:149,rating:4.7,pop:88,desc:'Chilled coffee, creamy foam and a hint of vanilla.',img:'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=800&q=80',veg:true},
{id:8,name:'Farmhouse Garden Pizza',restaurant:'Ember & Crust',category:'Pizza',price:319,rating:4.7,pop:87,desc:'Bell peppers, onion, mushrooms and fresh herbs.',img:'https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=800&q=80',veg:true},
{id:9,name:'Avocado Power Salad',restaurant:'Green Bowl Co.',category:'Healthy Meals',price:279,rating:4.8,pop:90,desc:'Avocado, greens, chickpeas, seeds and lemon dressing.',img:'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',veg:true},
{id:10,name:'Butter Chicken Bowl',restaurant:'Saffron Street',category:'Fast Food',price:329,rating:4.8,pop:95,desc:'Creamy tomato gravy, tender chicken and fragrant rice.',img:'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80',veg:false},
{id:11,name:'Strawberry Cheesecake',restaurant:'Ember & Crust',category:'Desserts',price:219,rating:4.8,pop:86,desc:'Silky cheesecake topped with fresh strawberry glaze.',img:'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=800&q=80',veg:true},
{id:12,name:'Sparkling Lime Cooler',restaurant:'Green Bowl Co.',category:'Beverages',price:129,rating:4.6,pop:84,desc:'Zesty lime, mint and sparkling refreshment.',img:'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80',veg:true}
];
const cats=[['Pizza','🍕'],['Burgers','🍔'],['Fast Food','🍟'],['Desserts','🍰'],['Beverages','🥤'],['Healthy Meals','🥗']];

function App(){
 const [dark,setDark]=useState(()=>localStorage.getItem('cravora-dark')==='1');
 const [cart,setCart]=useState(()=>JSON.parse(localStorage.getItem('cravora-cart')||'[]'));
 const [favs,setFavs]=useState(()=>JSON.parse(localStorage.getItem('cravora-favs')||'[]'));
 const [orders,setOrders]=useState(()=>JSON.parse(localStorage.getItem('cravora-orders')||'[]'));
 const [view,setView]=useState('home'); const [query,setQuery]=useState(''); const [cat,setCat]=useState('All'); const [sort,setSort]=useState('popular'); const [max,setMax]=useState(500); const [cartOpen,setCartOpen]=useState(false); const [profileOpen,setProfileOpen]=useState(false); const [toast,setToast]=useState(''); const [mobile,setMobile]=useState(false);
 useEffect(()=>{localStorage.setItem('cravora-dark',dark?'1':'0');document.documentElement.dataset.theme=dark?'dark':'light'},[dark]);
 useEffect(()=>localStorage.setItem('cravora-cart',JSON.stringify(cart)),[cart]); useEffect(()=>localStorage.setItem('cravora-favs',JSON.stringify(favs)),[favs]); useEffect(()=>localStorage.setItem('cravora-orders',JSON.stringify(orders)),[orders]);
 const notify=m=>{setToast(m);setTimeout(()=>setToast(''),2200)};
 const go=v=>{setView(v);setMobile(false);window.scrollTo({top:0,behavior:'smooth'})};
 const add=f=>{setCart(c=>{const x=c.find(i=>i.id===f.id);return x?c.map(i=>i.id===f.id?{...i,qty:i.qty+1}:i):[...c,{...f,qty:1}]});notify(`${f.name} added to cart`)};
 const change=(id,d)=>setCart(c=>c.map(i=>i.id===id?{...i,qty:i.qty+d}:i).filter(i=>i.qty>0));
 const toggleFav=id=>setFavs(f=>f.includes(id)?f.filter(x=>x!==id):[...f,id]);
 const filtered=useMemo(()=>{let a=foods.filter(f=>(cat==='All'||f.category===cat)&&f.price<=max&&(!query||`${f.name} ${f.restaurant}`.toLowerCase().includes(query.toLowerCase())));return [...a].sort((x,y)=>sort==='rating'?y.rating-x.rating:sort==='price'?x.price-y.price:y.pop-x.pop)},[query,cat,sort,max]);
 const total=cart.reduce((s,i)=>s+i.price*i.qty,0), delivery=total>=499||total===0?0:39, grand=total+delivery;
 return <div className="app">
  <Header dark={dark} setDark={setDark} go={go} view={view} query={query} setQuery={setQuery} cartCount={cart.reduce((s,i)=>s+i.qty,0)} setCartOpen={setCartOpen} profileOpen={profileOpen} setProfileOpen={setProfileOpen} mobile={mobile} setMobile={setMobile}/>
  {view==='home'&&<Home go={go} add={add} toggleFav={toggleFav} favs={favs} restaurants={restaurants} foods={foods} setCat={setCat} />}
  {view==='menu'&&<Menu filtered={filtered} query={query} setQuery={setQuery} cat={cat} setCat={setCat} sort={sort} setSort={setSort} max={max} setMax={setMax} add={add} favs={favs} toggleFav={toggleFav}/>} 
  {view==='restaurants'&&<Restaurants restaurants={restaurants} go={go}/>} 
  {view==='favorites'&&<Favorites foods={foods.filter(f=>favs.includes(f.id))} add={add} toggleFav={toggleFav}/>} 
  {view==='orders'&&<Orders orders={orders}/>} 
  {view==='checkout'&&<Checkout cart={cart} total={total} delivery={delivery} grand={grand} change={change} setCartOpen={setCartOpen} place={order=>{setOrders(o=>[order,...o]);setCart([]);go('orders');notify('Order placed successfully!')}}/>}
  {view==='profile'&&<Profile go={go} orders={orders} favs={favs}/>} 
  {view==='admin'&&<Admin orders={orders} foods={foods}/>} 
  <Footer go={go}/>
  {cartOpen&&<CartDrawer cart={cart} total={total} delivery={delivery} grand={grand} change={change} close={()=>setCartOpen(false)} checkout={()=>{setCartOpen(false);go('checkout')}}/>}
  {toast&&<div className="toast"><FaCheckCircle/> {toast}</div>}
 </div>
}

function Header({dark,setDark,go,view,query,setQuery,cartCount,setCartOpen,profileOpen,setProfileOpen,mobile,setMobile}){return <header className="header"><div className="nav wrap"><button className="brand" onClick={()=>go('home')}><span className="brand-mark"><FaUtensils/></span><span>Cra<span>vora</span></span></button><nav className={mobile?'nav-links open':'nav-links'}>{[['home','Home'],['menu','Menu'],['restaurants','Restaurants'],['favorites','Favorites'],['orders','Orders']].map(([v,t])=><button key={v} className={view===v?'active':''} onClick={()=>go(v)}>{t}</button>)}</nav><div className="nav-actions"><div className="mini-search"><FaSearch/><input value={query} onChange={e=>{setQuery(e.target.value);go('menu')}} placeholder="Search dishes..."/></div><button className="icon-btn" onClick={()=>setDark(!dark)} title="Toggle theme">{dark?<FaSun/>:<FaMoon/>}</button><button className="icon-btn cart-btn" onClick={()=>setCartOpen(true)}><FaShoppingBag/><b>{cartCount}</b></button><div className="profile-wrap"><button className="avatar" onClick={()=>setProfileOpen(!profileOpen)}><FaUser/></button>{profileOpen&&<div className="profile-pop"><button onClick={()=>go('profile')}><FaUser/> My Profile</button><button onClick={()=>go('admin')}><FaReceipt/> Admin Demo</button></div>}</div><button className="hamb" onClick={()=>setMobile(!mobile)}>{mobile?<FaTimes/>:<FaBars/>}</button></div></div></header>}

function Home({go,add,toggleFav,favs,restaurants,foods,setCat}){return <main>
 <section className="hero wrap"><div className="hero-copy"><div className="eyebrow"><FaBolt/> PREMIUM FOOD DELIVERY</div><h1>Delicious food,<br/><em>delivered to you.</em></h1><p>Discover the best restaurants and enjoy your favorite meals, delivered fresh to your door.</p><div className="hero-cta"><button className="primary" onClick={()=>go('menu')}>Order now <FaArrowRight/></button><button className="ghost" onClick={()=>go('restaurants')}>Browse restaurants</button></div><div className="hero-stats"><span><b>4.8/5</b><small>Average rating</small></span><span><b>30 min</b><small>Avg. delivery</small></span><span><b>10K+</b><small>Happy foodies</small></span></div></div><div className="hero-art"><div className="hero-orb"></div><div className="hero-card card-a"><FaTruck/><div><b>On the way</b><small>Arriving in 12 min</small></div></div><div className="hero-card card-b"><span className="dish-emoji">🍜</span><div><b>Chef's special</b><small>Trending near you</small></div><FaHeart/></div><div className="plate"><img src="https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1000&q=85"/></div></div></section>
 <section className="section wrap"><SectionTitle eyebrow="EXPLORE" title="What are you craving?" action="View all" onClick={()=>go('menu')}/><div className="cat-grid">{cats.map(([n,e])=><button key={n} className="cat-card" onClick={()=>{setCat(n);go('menu')}}><span>{e}</span><b>{n}</b><small>Explore →</small></button>)}</div></section>
 <section className="section wrap"><SectionTitle eyebrow="NEARBY FAVORITES" title="Popular restaurants" action="See all" onClick={()=>go('restaurants')}/><div className="restaurant-grid">{restaurants.slice(0,4).map(r=><RestaurantCard r={r} key={r.id}/>)}</div></section>
 <section className="promo wrap"><div><span className="eyebrow">LIMITED-TIME OFFER</span><h2>Flat 30% OFF on your first order</h2><p>Use code CRAVE30 and discover your next favorite meal.</p><button className="light-btn" onClick={()=>go('menu')}>Start ordering <FaArrowRight/></button></div><div className="promo-art">🥡</div></section>
 <section className="section wrap"><SectionTitle eyebrow="TRENDING NOW" title="People are loving these" action="Explore menu" onClick={()=>go('menu')}/><div className="food-grid">{foods.slice(0,4).map(f=><FoodCard f={f} add={add} favs={favs} toggleFav={toggleFav} key={f.id}/>)}</div></section>
 <section className="why wrap"><div><span className="eyebrow">THE BITEFLOW PROMISE</span><h2>More than food.<br/><em>A better way to order.</em></h2></div><div className="promise-grid"><Promise icon={<FaBolt/>} title="Lightning fast" text="Smart dispatch keeps your meal moving."/><Promise icon={<FaStar/>} title="Curated quality" text="Only the best-rated local picks."/><Promise icon={<FaHeart/>} title="Made for you" text="Personalized picks that learn your taste."/></div></section>
 </main>}
function SectionTitle({eyebrow,title,action,onClick}){return <div className="section-title"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{action&&<button className="text-btn" onClick={onClick}>{action} <FaArrowRight/></button>}</div>}
function RestaurantCard({r}){return <article className="restaurant-card"><div className="image-wrap"><img src={r.img}/><span className="tag">{r.tag}</span><span className={r.open?'status open':'status'}>{r.open?'● Open':'● Closed'}</span></div><div className="r-body"><div><h3>{r.name}</h3><p>{r.cuisine}</p></div><span className="rating"><FaStar/> {r.rating}</span></div><div className="r-meta"><span><FaClock/> {r.time}</span><span>{r.fee}</span></div></article>}
function FoodCard({f,add,favs,toggleFav}){return <article className="food-card"><div className="food-image"><img src={f.img}/><button className={favs.includes(f.id)?'heart liked':'heart'} onClick={()=>toggleFav(f.id)}><FaHeart/></button>{f.veg&&<span className="veg">VEG</span>}</div><div className="food-body"><div className="food-top"><span>{f.category}</span><span><FaStar/> {f.rating}</span></div><h3>{f.name}</h3><p>{f.desc}</p><div className="food-bottom"><strong>₹{f.price}</strong><button className="add" onClick={()=>add(f)}><FaPlus/> Add</button></div></div></article>}
function Menu({filtered,query,setQuery,cat,setCat,sort,setSort,max,setMax,add,favs,toggleFav}){return <main className="page wrap"><div className="page-head"><div><span className="eyebrow">DISCOVER YOUR NEXT FAVORITE</span><h1>Explore the menu</h1><p>Fresh picks from restaurants around you.</p></div><div className="big-search"><FaSearch/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search food or restaurant..."/></div></div><div className="filterbar"><div className="chips"><button className={cat==='All'?'chip active':'chip'} onClick={()=>setCat('All')}>All</button>{cats.map(([n])=><button className={cat===n?'chip active':'chip'} onClick={()=>setCat(n)} key={n}>{n}</button>)}</div><div className="sort"><span>Sort:</span><select value={sort} onChange={e=>setSort(e.target.value)}><option value="popular">Most popular</option><option value="rating">Top rated</option><option value="price">Price: low to high</option></select><span className="range">₹0 — ₹{max}</span><input type="range" min="100" max="500" step="10" value={max} onChange={e=>setMax(+e.target.value)}/></div></div><div className="result-line"><b>{filtered.length} dishes</b><span>Curated for you</span></div><div className="food-grid large">{filtered.map(f=><FoodCard f={f} add={add} favs={favs} toggleFav={toggleFav} key={f.id}/>)}</div>{!filtered.length&&<Empty title="No dishes found" text="Try another search or category."/>}</main>}
function Restaurants({restaurants,go}){return <main className="page wrap"><div className="page-head"><div><span className="eyebrow">LOCAL & LOVELY</span><h1>Restaurants</h1><p>Find your next go-to spot.</p></div><button className="primary" onClick={()=>go('menu')}>Explore food <FaArrowRight/></button></div><div className="restaurant-grid large">{restaurants.map(r=><RestaurantCard r={r} key={r.id}/>)}</div></main>}
function Favorites({foods,add,toggleFav}){return <main className="page wrap"><div className="page-head"><div><span className="eyebrow">SAVED FOR LATER</span><h1>Your favorites</h1><p>All the dishes you don't want to forget.</p></div></div>{foods.length?<div className="food-grid large">{foods.map(f=><FoodCard f={f} add={add} favs={foods.map(x=>x.id)} toggleFav={toggleFav} key={f.id}/>)}</div>:<Empty title="Your favorites are waiting" text="Tap the heart on any dish to save it here."/>}</main>}
function Orders({orders}){return <main className="page wrap"><div className="page-head"><div><span className="eyebrow">YOUR BITES</span><h1>Order history</h1><p>Every delicious decision, in one place.</p></div></div>{orders.length?<div className="orders-list">{orders.map(o=><div className="order-card" key={o.id}><div className="order-icon"><FaReceipt/></div><div className="order-main"><div className="order-row"><div><b>Order #{o.id}</b><span>{new Date(o.date).toLocaleString()}</span></div><strong>₹{o.total}</strong></div><p>{o.items.map(i=>`${i.qty}× ${i.name}`).join(' • ')}</p><div className="progress"><span style={{width:o.status==='Delivered'?'100%':'65%'}}></span></div><div className="order-status"><span><FaCheckCircle/> {o.status}</span><span>{o.address}</span></div></div></div>)}</div>:<Empty title="No orders yet" text="Your next great meal is one tap away."/>}</main>}
function Checkout({cart,total,delivery,grand,change,setCartOpen,place}){const [form,setForm]=useState({name:'',phone:'',address:'',city:'Bengaluru',note:'',pay:'UPI'});const [error,setError]=useState('');const submit=e=>{e.preventDefault();if(!cart.length){setError('Your cart is empty.');return}if(!form.name||!form.phone||!form.address){setError('Please fill all required fields.');return}if(!/^[6-9]\d{9}$/.test(form.phone)){setError('Enter a valid 10-digit Indian mobile number.');return}place({id:'BF'+Date.now().toString().slice(-6),date:new Date().toISOString(),items:cart,total:grand,address:form.address,status:'Preparing',customer:form,payment:form.pay})};return <main className="page wrap checkout"><div className="page-head"><div><span className="eyebrow">ALMOST THERE</span><h1>Complete your order</h1><p>Fresh food is just a few details away.</p></div></div><div className="checkout-grid"><form className="form-card" onSubmit={submit}><h2>Delivery details</h2><div className="form-grid"><label>Full name*<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Your name"/></label><label>Mobile number*<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value.replace(/\D/g,'').slice(0,10)})} placeholder="10-digit number"/></label></div><label>Delivery address*<textarea value={form.address} onChange={e=>setForm({...form,address:e.target.value})} placeholder="House / flat, street, area"/></label><div className="form-grid"><label>City<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>Payment method<select value={form.pay} onChange={e=>setForm({...form,pay:e.target.value})}><option>UPI</option><option>Card</option><option>Cash on delivery</option></select></label></div><label>Delivery note <input value={form.note} onChange={e=>setForm({...form,note:e.target.value})} placeholder="e.g. Leave at the door"/></label>{error&&<div className="error">{error}</div>}<button className="primary wide" type="submit"><FaCreditCard/> Place order • ₹{grand}</button></form><div className="summary-card"><div className="summary-head"><h2>Order summary</h2><button onClick={()=>setCartOpen(true)}>{cart.reduce((s,i)=>s+i.qty,0)} items</button></div>{cart.length?cart.map(i=><div className="summary-item" key={i.id}><img src={i.img}/><div><b>{i.name}</b><small>₹{i.price} each</small><div className="qty"><button onClick={()=>change(i.id,-1)}><FaMinus/></button><span>{i.qty}</span><button onClick={()=>change(i.id,1)}><FaPlus/></button></div></div><strong>₹{i.price*i.qty}</strong></div>):<p className="muted">Your cart is empty.</p>}<div className="totals"><span>Subtotal <b>₹{total}</b></span><span>Delivery <b>{delivery?'₹'+delivery:'FREE'}</b></span><span className="grand">Total <b>₹{grand}</b></span></div></div></div></main>}
function CartDrawer({cart,total,delivery,grand,change,close,checkout}){return <div className="overlay" onClick={close}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><div><span className="eyebrow">YOUR BAG</span><h2>Order basket</h2></div><button className="close" onClick={close}><FaTimes/></button></div>{cart.length?<><div className="drawer-items">{cart.map(i=><div className="drawer-item" key={i.id}><img src={i.img}/><div><b>{i.name}</b><small>{i.restaurant}</small><strong>₹{i.price}</strong><div className="qty"><button onClick={()=>change(i.id,-1)}><FaMinus/></button><span>{i.qty}</span><button onClick={()=>change(i.id,1)}><FaPlus/></button></div></div></div>)}</div><div className="drawer-bottom"><div className="totals"><span>Subtotal <b>₹{total}</b></span><span>Delivery <b>{delivery?'₹'+delivery:'FREE'}</b></span><span className="grand">Total <b>₹{grand}</b></span></div><button className="primary wide" onClick={checkout}>Checkout <FaArrowRight/></button></div></>:<div className="empty-cart"><span>🛍️</span><h3>Your basket is empty</h3><p>Add something delicious and we'll take it from there.</p><button className="primary" onClick={close}>Start exploring</button></div>}</aside></div>}
function Profile({go,orders,favs}){return <main className="page wrap"><div className="profile-hero"><div className="profile-avatar"><FaUser/></div><div><span className="eyebrow">WELCOME BACK</span><h1>Foodie profile</h1><p>Your personal Cravora space.</p></div><button className="primary" onClick={()=>go('menu')}>Order something <FaArrowRight/></button></div><div className="stat-grid"><Stat n={orders.length} t="Orders placed"/><Stat n={favs.length} t="Favorite dishes"/><Stat n="4.9★" t="Your taste score"/></div><div className="profile-panels"><div className="panel"><FaMapMarkerAlt/><div><b>Default address</b><p>Set your delivery address during checkout.</p></div></div><div className="panel"><FaWallet/><div><b>Payment preferences</b><p>UPI, cards and cash on delivery supported.</p></div></div></div></main>}
function Admin({orders,foods}){return <main className="page wrap"><div className="page-head"><div><span className="eyebrow">DEMO DASHBOARD</span><h1>Admin overview</h1><p>A simple UI to demonstrate order management.</p></div></div><div className="admin-grid"><Stat n={orders.length} t="Total orders"/><Stat n={foods.length} t="Menu items"/><Stat n="₹48.2K" t="Demo revenue"/><Stat n="4.8★" t="Avg. rating"/></div><div className="admin-card"><h2>Recent orders</h2>{orders.length?orders.slice(0,5).map(o=><div className="admin-row" key={o.id}><span>#{o.id}</span><span>{o.items.length} items</span><b>₹{o.total}</b><span className="pill">{o.status}</span></div>):<p className="muted">Orders placed by customers will appear here.</p>}</div></main>}
function Stat({n,t}){return <div className="stat"><strong>{n}</strong><span>{t}</span></div>}function Promise({icon,title,text}){return <div className="promise"><span>{icon}</span><div><h3>{title}</h3><p>{text}</p></div></div>}
function Empty({title,text}){return <div className="empty"><div>🍽️</div><h2>{title}</h2><p>{text}</p></div>}
function Footer({go}){return <footer><div className="wrap footer-grid"><div><button className="brand footer-brand" onClick={()=>go('home')}><span className="brand-mark"><FaUtensils/></span><span>Cra<span>vora</span></span></button><p>Good food. Great mood.<br/>Delivered with care.</p><div className="socials"><a><FaInstagram/></a><a><FaFacebookF/></a><a><FaTwitter/></a><a><FaGithub/></a></div></div><div><h4>Explore</h4><button onClick={()=>go('menu')}>Menu</button><button onClick={()=>go('restaurants')}>Restaurants</button><button onClick={()=>go('favorites')}>Favorites</button></div><div><h4>Help</h4><button>Contact us</button><button>Delivery info</button><button>Terms & privacy</button></div><div className="newsletter"><h4>Stay in the loop</h4><p>Get weekly food inspiration & offers.</p><div><input placeholder="Email address"/><button><FaArrowRight/></button></div></div></div><div className="wrap footer-bottom"><span>© 2026 Cravora. Crafted for food lovers.</span><span>Made with React • Vite • CSS</span></div></footer>}
createRoot(document.getElementById('root')).render(<App/>);
